image: Visual Studio 2017
clone_folder: c:\projects\shut

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Win64
      COMPILER: vs
      MSVC_SETUP_ARG: x64

install:
  # Use Miniconda to accelerate the build (max time for CI is 60 minutes!)
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "python --version"
  - "pip --version"
  - "SET PROFILE=C:\\Users\\appveyor\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"

  - git submodule -q update --init --recursive

before_build:
  - cd C:\projects\shut

build_script:
  - ps: .\install.ps1 -y

# on_finish:
  # - "SET PROFILE=C:\\Users\\appveyor\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
  # - . "$PROFILE"
  # - refreshenv

  # - g++ --version
  # - make --version
  # - C:\\Users\\appveyor\\toolchain\\cmake\\bin\\cmake.exe --version
  # - C:\\Users\\appveyor\\toolchain\\Miniconda3\\python.exe --version
  # - C:\\Users\\appveyor\\toolchain\\Miniconda3\\Scripts\\conda.exe --version
  # - C:\\Users\\appveyor\\toolchain\\ninja\\ninja.exe --version
  # - C:\\Users\\appveyor\\toolchain\\chocolatey\\bin\\choco --version
  # - sublime --version
